# Generated by Django 4.2.1 on 2023-09-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="selected_service",
            new_name="selectedService",
        ),
        migrations.AlterField(
            model_name="booking",
            name="address",
            field=models.TextField(max_length=200),
        ),
    ]
